### ISSUE TITLE
Come up with a name for npm

### ISSUE THREAD

**Issue by benogle** [pipelinedb/stride.js#2]
`stride` is [taken](https://www.npmjs.com/package/stride), so we need something else.

`stride-js`?

**Comment by benogle** [comment]
We could use a [scoped package](https://docs.npmjs.com/getting-started/scoped-packages). e.g. could be `@pipelinedb/stride`

**Comment by usmanm** [comment]
Scoped package seems better? I'm not sure what the best practices here are. Your call!

**Comment by benogle** [comment]
Yeah, think i'm going to do the scoped package.
